/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing a schema.

/**
 * An organization or sub-element that performs tasking, coordination, or reporting functions (Section 6 of ARCHITECTURE.md) — distinct from the units that execute missions.
 */
export interface C2Node {
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type.
   */
  id: string;
  name: string;
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type.
   */
  organizationId: string;
  function: "Tasking" | "Coordination" | "Reporting" | "ExecutionMonitoring";
  /**
   * e.g. 'Air Tasking Order (ATO)', 'SPINS', 'Airspace Control Order (ACO)', 'Mission tasking'.
   */
  producesArtifacts?: string[];
  description?: string;
  /**
   * @minItems 1
   */
  doctrineSource: [DoctrineSource, ...DoctrineSource[]];
}
/**
 * Citation to the public doctrine or reference material that grounds this record. Required on every ENSIM entity per AGENTS.md — do not add a record without one, and use the 'note' field to flag anything not independently verified.
 */
export interface DoctrineSource {
  /**
   * e.g. 'AFDP 3-0.1', 'JP 3-17', 'DAFMAN 13-217', 'DoDD 5100.46', or a named fact sheet/article title.
   */
  publication: string;
  /**
   * Specific section, page, or fact-sheet heading, if applicable.
   */
  section?: string;
  url?: string;
  /**
   * Free-text caveat, e.g. 'unit designation not yet verified — confirm before treating as fact.'
   */
  note?: string;
}
