/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing a schema.

/**
 * A choice point a Role makes during mission execution, given specific information inputs (informedBy) and criteria — a finer grain than DoctrineProcess (organizational tasking) or Interaction (a structural edge): what a person actually has to decide, not just who they talk to. See ARCHITECTURE.md Section 6.
 */
export interface Decision {
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type.
   */
  id: string;
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type.
   */
  roleId: string;
  name: string;
  description: string;
  /**
   * The nodes (roles, systems, etc.) whose information feeds this decision.
   *
   * @minItems 1
   */
  informedBy: [Participant, ...Participant[]];
  /**
   * What determines the outcome — the standard the Role applies.
   */
  criteria: string;
  /**
   * @minItems 1
   */
  possibleOutcomes: [string, ...string[]];
  /**
   * @minItems 1
   */
  doctrineSource: [DoctrineSource, ...DoctrineSource[]];
}
/**
 * A reference to any node in the mission execution interaction network — a Role (personnel), C2Node, Organization, or System.
 */
export interface Participant {
  kind: "role" | "c2node" | "organization" | "system";
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type.
   */
  id: string;
}
/**
 * Citation to the public doctrine or reference material that grounds this record. Required on every ENSIM entity per AGENTS.md — do not add a record without one, and use the 'note' field to flag anything not independently verified.
 */
export interface DoctrineSource {
  /**
   * e.g. 'AFDP 3-0.1', 'JP 3-17', 'DAFMAN 13-217', 'DoDD 5100.46', or a named fact sheet/article title.
   */
  publication: string;
  /**
   * Specific section, page, or fact-sheet heading, if applicable.
   */
  section?: string;
  url?: string;
  /**
   * Free-text caveat, e.g. 'unit designation not yet verified — confirm before treating as fact.'
   */
  note?: string;
}
