/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing a schema.

/**
 * A named, sequenced process with the roles/nodes involved at each step and the artifacts produced (Section 6 of ARCHITECTURE.md).
 */
export interface DoctrineProcess {
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type.
   */
  id: string;
  name: string;
  description?: string;
  /**
   * @minItems 1
   */
  steps: [
    {
      stepNumber: number;
      description: string;
      actorRoleId?: string | null;
      actorC2NodeId?: string | null;
      /**
       * Use when the actor is an organization as a whole rather than a specific role or C2 node (e.g. 'INDOPACOM stands up a Joint Task Force').
       */
      actorOrganizationId?: string | null;
      producesArtifact?: string | null;
    },
    ...{
      stepNumber: number;
      description: string;
      actorRoleId?: string | null;
      actorC2NodeId?: string | null;
      /**
       * Use when the actor is an organization as a whole rather than a specific role or C2 node (e.g. 'INDOPACOM stands up a Joint Task Force').
       */
      actorOrganizationId?: string | null;
      producesArtifact?: string | null;
    }[]
  ];
  /**
   * @minItems 1
   */
  doctrineSource: [DoctrineSource, ...DoctrineSource[]];
}
/**
 * Citation to the public doctrine or reference material that grounds this record. Required on every ENSIM entity per AGENTS.md — do not add a record without one, and use the 'note' field to flag anything not independently verified.
 */
export interface DoctrineSource {
  /**
   * e.g. 'AFDP 3-0.1', 'JP 3-17', 'DAFMAN 13-217', 'DoDD 5100.46', or a named fact sheet/article title.
   */
  publication: string;
  /**
   * Specific section, page, or fact-sheet heading, if applicable.
   */
  section?: string;
  url?: string;
  /**
   * Free-text caveat, e.g. 'unit designation not yet verified — confirm before treating as fact.'
   */
  note?: string;
}
