/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing a schema.

/**
 * A specific tasking instance that references the organizations, roles, and doctrine process that generated it, plus mission-specific parameters (Section 6/7 of ARCHITECTURE.md).
 */
export interface Mission {
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type.
   */
  id: string;
  name: string;
  status: "Draft" | "Tasked" | "Executing" | "Complete";
  /**
   * Must be true for any scenario grounded in real precedent but not an actual mission — see AGENTS.md classification-boundary rules.
   */
  fictionalized: boolean;
  /**
   * Real-world operation this scenario is doctrinally/geographically modeled on, if any.
   */
  precedent?: string;
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type.
   */
  doctrineProcessId: string;
  /**
   * @minItems 1
   *
   * Items: Lowercase kebab-case stable identifier, unique within its entity type.
   */
  organizationsInvolved: [string, ...string[]];
  /**
   * Items: Lowercase kebab-case stable identifier, unique within its entity type.
   */
  rolesInvolved?: string[];
  route?: {
    origin: string;
    destination: string;
    stagingNote?: string;
  };
  cargo?: {
    type?: string;
    contents?: string;
    bundleCount?: number | null;
  };
  /**
   * For aeromedical evacuation missions, in place of cargo — see AE Decision/Interaction records for patient precedence (Urgent/Urgent-Surg/Priority/Routine/Convenience) and type (Litter/Ambulatory).
   */
  patients?: {
    type?: string;
    contents?: string;
    count?: number | null;
    litterCount?: number | null;
    ambulatoryCount?: number | null;
    precedenceMix?: string;
  };
  /**
   * Discrete-event steps for the v1 data/process simulation (Section 4a/7 of ARCHITECTURE.md) — not a flown trajectory.
   *
   * @minItems 1
   */
  timeline: [
    {
      step: number;
      description: string;
      /**
       * stepNumber this corresponds to in the referenced DoctrineProcess, if applicable.
       */
      doctrineProcessStep?: number | null;
    },
    ...{
      step: number;
      description: string;
      /**
       * stepNumber this corresponds to in the referenced DoctrineProcess, if applicable.
       */
      doctrineProcessStep?: number | null;
    }[]
  ];
  /**
   * @minItems 1
   */
  doctrineSource: [DoctrineSource, ...DoctrineSource[]];
}
/**
 * Citation to the public doctrine or reference material that grounds this record. Required on every ENSIM entity per AGENTS.md — do not add a record without one, and use the 'note' field to flag anything not independently verified.
 */
export interface DoctrineSource {
  /**
   * e.g. 'AFDP 3-0.1', 'JP 3-17', 'DAFMAN 13-217', 'DoDD 5100.46', or a named fact sheet/article title.
   */
  publication: string;
  /**
   * Specific section, page, or fact-sheet heading, if applicable.
   */
  section?: string;
  url?: string;
  /**
   * Free-text caveat, e.g. 'unit designation not yet verified — confirm before treating as fact.'
   */
  note?: string;
}
