/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing a schema.

/**
 * A piece of equipment or infrastructure that personnel (Roles) interact with during mission execution — an aircraft, a communications system, a security/access-control system, an airdrop mechanism. Deliberately representative, not a real fielded system's actual specifications — see AGENTS.md Section 3, the classification boundary. Systems are nodes in the mission execution interaction network alongside Roles, C2Nodes, and Organizations (see Interaction).
 */
export interface System {
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type.
   */
  id: string;
  name: string;
  type: "Aircraft" | "Communications" | "SecurityAccessControl" | "AirdropMechanism" | "MedicalEquipment";
  description: string;
  /**
   * @minItems 1
   */
  doctrineSource: [DoctrineSource, ...DoctrineSource[]];
}
/**
 * Citation to the public doctrine or reference material that grounds this record. Required on every ENSIM entity per AGENTS.md — do not add a record without one, and use the 'note' field to flag anything not independently verified.
 */
export interface DoctrineSource {
  /**
   * e.g. 'AFDP 3-0.1', 'JP 3-17', 'DAFMAN 13-217', 'DoDD 5100.46', or a named fact sheet/article title.
   */
  publication: string;
  /**
   * Specific section, page, or fact-sheet heading, if applicable.
   */
  section?: string;
  url?: string;
  /**
   * Free-text caveat, e.g. 'unit designation not yet verified — confirm before treating as fact.'
   */
  note?: string;
}
