/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/run-result.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing the schema.

/**
 * The output of running a Mission scenario through sim-services' discrete-event runner (ARCHITECTURE.md Section 11/13). This is the 'run-result' data contract Section 13 deferred until sim-services was scoped: the planned-timeline shape (Mission.timeline) plus execution fields (status, simulated timestamp, artifact reference) so model-explorer's v2 results view can render it without being rebuilt.
 */
export interface RunResult {
  /**
   * Unique per execution, e.g. '<missionId>-<ISO timestamp>'.
   */
  runId: string;
  /**
   * id of the org-doctrine-model Mission record this run executed.
   */
  missionId: string;
  /**
   * id of the DoctrineProcess the Mission references, for cross-referencing step artifacts.
   */
  doctrineProcessId: string;
  status: "Complete" | "Failed";
  /**
   * Wall-clock time the run started (real time, not simulated).
   */
  startedAt: string;
  /**
   * Wall-clock time the run finished (real time, not simulated).
   */
  completedAt: string;
  /**
   * Whether this run's per-step state was published to the org-doctrine-model HLA federation via federation-kernel. False when federation-kernel's jar wasn't available - see sim-services README.
   */
  federationPublished: boolean;
  /**
   * @minItems 1
   */
  steps: [
    {
      /**
       * Matches the corresponding Mission.timeline[].step.
       */
      step: number;
      description: string;
      /**
       * stepNumber in the referenced DoctrineProcess this corresponds to, if any - matches Mission.timeline[].doctrineProcessStep.
       */
      doctrineProcessStep?: number | null;
      /**
       * Mission 1 v1's runner is a linear discrete-event sequence with no retry/failure branching yet - every step that ran reaches Complete. Failure at the run level is reported via the top-level 'status' field, not per-step.
       */
      status: "Complete";
      /**
       * Logical/simulated time this step occurred, decoupled from wall-clock run time - see sim-services README for why.
       */
      simulatedTimestamp: string;
      /**
       * The DoctrineProcess step's producesArtifact, when doctrineProcessStep resolves to one - null otherwise.
       */
      artifactProduced: string | null;
    },
    ...{
      /**
       * Matches the corresponding Mission.timeline[].step.
       */
      step: number;
      description: string;
      /**
       * stepNumber in the referenced DoctrineProcess this corresponds to, if any - matches Mission.timeline[].doctrineProcessStep.
       */
      doctrineProcessStep?: number | null;
      /**
       * Mission 1 v1's runner is a linear discrete-event sequence with no retry/failure branching yet - every step that ran reaches Complete. Failure at the run level is reported via the top-level 'status' field, not per-step.
       */
      status: "Complete";
      /**
       * Logical/simulated time this step occurred, decoupled from wall-clock run time - see sim-services README for why.
       */
      simulatedTimestamp: string;
      /**
       * The DoctrineProcess step's producesArtifact, when doctrineProcessStep resolves to one - null otherwise.
       */
      artifactProduced: string | null;
    }[]
  ];
}
