// Generates TypeScript types from the JSON Schema in schema/ so consumers
// (e.g. apps/model-explorer) never hand-write a duplicate type definition
// that could drift from the schema — see AGENTS.md Section 5.
// Run with: npm run generate-types  (from packages/org-doctrine-model)
import { compileFromFile } from "json-schema-to-typescript";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const schemaDir = path.join(here, "..", "schema");
const outDir = path.join(here, "..", "types");

mkdirSync(outDir, { recursive: true });

const schemas = [
  { file: "organization.schema.json", name: "Organization" },
  { file: "role.schema.json", name: "Role" },
  { file: "c2node.schema.json", name: "C2Node" },
  { file: "doctrine-process.schema.json", name: "DoctrineProcess" },
  { file: "mission.schema.json", name: "Mission" },
  { file: "system.schema.json", name: "System" },
  { file: "interaction.schema.json", name: "Interaction" },
  { file: "decision.schema.json", name: "Decision" },
];

const banner =
  "/* eslint-disable */\n" +
  "// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —\n" +
  "// run `npm run generate-types` after changing a schema.\n\n";

const exportLines = [];

for (const { file, name } of schemas) {
  const ts = await compileFromFile(path.join(schemaDir, file), {
    cwd: schemaDir,
    bannerComment: "",
    additionalProperties: false,
    style: { semi: true },
  });
  writeFileSync(path.join(outDir, `${name}.ts`), banner + ts);
  exportLines.push(`export type { ${name} } from "./${name}.js";`);
  console.log(`wrote types/${name}.ts`);
}

exportLines.push('export type { DoctrineSource } from "./Organization.js";');
writeFileSync(path.join(outDir, "index.ts"), banner + exportLines.join("\n") + "\n");
console.log("wrote types/index.ts");
