// Generates TypeScript types from schema/*.schema.json so nothing hand-duplicates them
// (AGENTS.md Section 5). Mirrors packages/org-doctrine-model/scripts/generate-types.mjs.
// Run with: npm run generate-types  (from packages/c2-interfaces)
import { compileFromFile } from "json-schema-to-typescript";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const schemaDir = path.join(here, "..", "schema");
const outDir = path.join(here, "..", "types");

mkdirSync(outDir, { recursive: true });

const schemas = [
  { file: "tasking-request.schema.json", name: "TaskingRequest" },
  { file: "validation-record.schema.json", name: "ValidationRecord" },
  { file: "ato-line.schema.json", name: "ATOLine" },
  { file: "execution-status.schema.json", name: "ExecutionStatus" },
  { file: "mission-report.schema.json", name: "MissionReport" },
];

const banner =
  "/* eslint-disable */\n" +
  "// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —\n" +
  "// run `npm run generate-types` after changing a schema.\n\n";

const exportLines = [];

for (const { file, name } of schemas) {
  const ts = await compileFromFile(path.join(schemaDir, file), {
    cwd: schemaDir,
    bannerComment: "",
    additionalProperties: false,
    style: { semi: true },
  });
  writeFileSync(path.join(outDir, `${name}.ts`), banner + ts);
  exportLines.push(`export type { ${name} } from "./${name}.js";`);
  console.log(`wrote types/${name}.ts`);
}

exportLines.push('export type { DoctrineSource } from "./TaskingRequest.js";');
writeFileSync(path.join(outDir, "index.ts"), banner + exportLines.join("\n") + "\n");
console.log("wrote types/index.ts");
