/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing a schema.

/**
 * The 'ATO line' phase of ENSIM's tasking sequence (ARCHITECTURE.md Section 3). Grounded in org-doctrine-model's hadr-request-and-tasking-flow doctrine process, step 5 ('ATO line', produced by the Air Mobility Division) and the ato-cycle doctrine process generally. Deliberately representative, not a real Air Tasking Order line format (USMTF/fixed-column ATO fields are not modeled — see AGENTS.md Section 3, the classification boundary).
 */
export interface ATOLine {
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type. Same convention as org-doctrine-model's common.schema.json — deliberately not $ref'd across packages, to keep c2-interfaces self-contained (see README).
   */
  id: string;
  messageType: "ATOLine";
  timestamp: string;
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type. Same convention as org-doctrine-model's common.schema.json — deliberately not $ref'd across packages, to keep c2-interfaces self-contained (see README).
   */
  missionId: string;
  doctrineProcessStep?: number | null;
  producedBy?: Actor;
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type. Same convention as org-doctrine-model's common.schema.json — deliberately not $ref'd across packages, to keep c2-interfaces self-contained (see README).
   */
  taskedOrganizationId: string;
  taskingSummary: string;
  effectiveDate?: string;
  /**
   * @minItems 1
   */
  doctrineSource: [DoctrineSource, ...DoctrineSource[]];
}
/**
 * Who produced this message — mirrors org-doctrine-model DoctrineProcess step's actorRoleId/actorC2NodeId/actorOrganizationId pattern (usually exactly one is set).
 */
export interface Actor {
  roleId?: string | null;
  c2NodeId?: string | null;
  organizationId?: string | null;
}
/**
 * Citation to the public doctrine or reference material that grounds this message type or record. Required per AGENTS.md Section 2, which explicitly calls out 'a C2 interface' alongside the org/doctrine model and mission scenarios — not optional style.
 */
export interface DoctrineSource {
  publication: string;
  section?: string;
  url?: string;
  note?: string;
}
