/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing a schema.

/**
 * The 'execution' phase of ENSIM's tasking sequence (ARCHITECTURE.md Section 3). Grounded in Mission 1's timeline step 7 ('Sortie generated and mission executed'). Discrete sortie states only — no real-time position/telemetry, matching Mission 1 v1's explicit scope (data/process simulation, not flight dynamics; ARCHITECTURE.md Section 4a/7).
 */
export interface ExecutionStatus {
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type. Same convention as org-doctrine-model's common.schema.json — deliberately not $ref'd across packages, to keep c2-interfaces self-contained (see README).
   */
  id: string;
  messageType: "ExecutionStatus";
  timestamp: string;
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type. Same convention as org-doctrine-model's common.schema.json — deliberately not $ref'd across packages, to keep c2-interfaces self-contained (see README).
   */
  missionId: string;
  doctrineProcessStep?: number | null;
  producedBy?: Actor;
  /**
   * Representative discrete states, not a real sortie-status message standard.
   */
  sortieStatus: "Generated" | "Airborne" | "OnStation" | "DropComplete" | "Returned";
  statusNote?: string;
  /**
   * @minItems 1
   */
  doctrineSource: [DoctrineSource, ...DoctrineSource[]];
}
/**
 * Who produced this message — mirrors org-doctrine-model DoctrineProcess step's actorRoleId/actorC2NodeId/actorOrganizationId pattern (usually exactly one is set).
 */
export interface Actor {
  roleId?: string | null;
  c2NodeId?: string | null;
  organizationId?: string | null;
}
/**
 * Citation to the public doctrine or reference material that grounds this message type or record. Required per AGENTS.md Section 2, which explicitly calls out 'a C2 interface' alongside the org/doctrine model and mission scenarios — not optional style.
 */
export interface DoctrineSource {
  publication: string;
  section?: string;
  url?: string;
  note?: string;
}
