/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing a schema.

/**
 * The initiating message in ENSIM's representative tasking sequence (ARCHITECTURE.md Section 3: request → validate → ATO line → execution → report) — a host-nation or embassy request for assistance. Grounded in org-doctrine-model's hadr-request-and-tasking-flow doctrine process, step 1 ('Assistance request').
 */
export interface TaskingRequest {
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type. Same convention as org-doctrine-model's common.schema.json — deliberately not $ref'd across packages, to keep c2-interfaces self-contained (see README).
   */
  id: string;
  messageType: "TaskingRequest";
  timestamp: string;
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type. Same convention as org-doctrine-model's common.schema.json — deliberately not $ref'd across packages, to keep c2-interfaces self-contained (see README).
   */
  missionId: string;
  /**
   * stepNumber in the referenced Mission's DoctrineProcess this message corresponds to.
   */
  doctrineProcessStep?: number | null;
  producedBy?: Actor;
  /**
   * Free text, e.g. 'Philippine government / U.S. Embassy Manila' — not a role/org id, since the requester is external to the org-doctrine-model hierarchy this scenario models.
   */
  requestingParty: string;
  requestSummary: string;
  /**
   * @minItems 1
   */
  doctrineSource: [DoctrineSource, ...DoctrineSource[]];
}
/**
 * Who produced this message — mirrors org-doctrine-model DoctrineProcess step's actorRoleId/actorC2NodeId/actorOrganizationId pattern (usually exactly one is set).
 */
export interface Actor {
  roleId?: string | null;
  c2NodeId?: string | null;
  organizationId?: string | null;
}
/**
 * Citation to the public doctrine or reference material that grounds this message type or record. Required per AGENTS.md Section 2, which explicitly calls out 'a C2 interface' alongside the org/doctrine model and mission scenarios — not optional style.
 */
export interface DoctrineSource {
  publication: string;
  section?: string;
  url?: string;
  note?: string;
}
