/* eslint-disable */
// Generated by scripts/generate-types.mjs from schema/*.schema.json. Do not hand-edit —
// run `npm run generate-types` after changing a schema.

/**
 * The 'validate' phase of ENSIM's tasking sequence (ARCHITECTURE.md Section 3). Covers the three coordination/approval artifacts between the initial request and the ATO line in org-doctrine-model's hadr-request-and-tasking-flow doctrine process (steps 2-4): requirement validation, tasking-authority approval, and Joint Task Force stand-up. One schema, distinguished by recordType, rather than three near-identical schemas — these are all 'someone in the chain validated/approved something' shaped.
 */
export interface ValidationRecord {
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type. Same convention as org-doctrine-model's common.schema.json — deliberately not $ref'd across packages, to keep c2-interfaces self-contained (see README).
   */
  id: string;
  messageType: "ValidationRecord";
  /**
   * Maps to doctrine-processes.json hadr-request-and-tasking-flow step 2 ('Validated requirement'), step 3 ('Approved tasking authority'), and step 4 ('Joint Task Force stand-up order') respectively.
   */
  recordType: "RequirementValidated" | "TaskingAuthorityApproved" | "JointTaskForceStoodUp";
  timestamp: string;
  /**
   * Lowercase kebab-case stable identifier, unique within its entity type. Same convention as org-doctrine-model's common.schema.json — deliberately not $ref'd across packages, to keep c2-interfaces self-contained (see README).
   */
  missionId: string;
  doctrineProcessStep?: number | null;
  producedBy?: Actor;
  summary: string;
  /**
   * @minItems 1
   */
  doctrineSource: [DoctrineSource, ...DoctrineSource[]];
}
/**
 * Who produced this message — mirrors org-doctrine-model DoctrineProcess step's actorRoleId/actorC2NodeId/actorOrganizationId pattern (usually exactly one is set).
 */
export interface Actor {
  roleId?: string | null;
  c2NodeId?: string | null;
  organizationId?: string | null;
}
/**
 * Citation to the public doctrine or reference material that grounds this message type or record. Required per AGENTS.md Section 2, which explicitly calls out 'a C2 interface' alongside the org/doctrine model and mission scenarios — not optional style.
 */
export interface DoctrineSource {
  publication: string;
  section?: string;
  url?: string;
  note?: string;
}
