// Generates TypeScript types from schema/run-result.schema.json so nothing hand-duplicates it
// (AGENTS.md Section 5) - mirrors packages/org-doctrine-model/scripts/generate-types.mjs.
// Run with: npm run generate-types  (from packages/sim-services)
import { compileFromFile } from "json-schema-to-typescript";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const schemaDir = path.join(here, "..", "schema");
const outDir = path.join(here, "..", "src", "types");

mkdirSync(outDir, { recursive: true });

const banner =
  "/* eslint-disable */\n" +
  "// Generated by scripts/generate-types.mjs from schema/run-result.schema.json. Do not hand-edit —\n" +
  "// run `npm run generate-types` after changing the schema.\n\n";

const ts = await compileFromFile(path.join(schemaDir, "run-result.schema.json"), {
  cwd: schemaDir,
  bannerComment: "",
  additionalProperties: false,
  style: { semi: true },
});

writeFileSync(path.join(outDir, "RunResult.ts"), banner + ts);
console.log("wrote types/RunResult.ts");
